### ISSUE TITLE
通用版本生成代码执行之后遇到如下错误，请指教

### ISSUE THREAD

**Issue by FeiNoLabel** [JiehangXie/PaddleBoBo#16]
/home/skzeng/anaconda3/envs/pp-bd/lib/python3.7/site-packages/librosa/core/constantq.py:1059: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.complex,
Traceback (most recent call last):
  File "general_demo.py", line 6, in <module>
    from PaddleTools.TTS import TTSExecutor
  File "/home/skzeng/AdoingPro/PaddleBoBo-develop/PaddleTools/TTS.py", line 10, in <module>
    from paddlespeech.cli.utils import download_and_decompress
  File "/home/skzeng/anaconda3/envs/pp-bd/lib/python3.7/site-packages/paddlespeech/cli/__init__.py", line 22, in <module>
    from .tts import TTSExecutor
  File "/home/skzeng/anaconda3/envs/pp-bd/lib/python3.7/site-packages/paddlespeech/cli/tts/__init__.py", line 14, in <module>
    from .infer import TTSExecutor
  File "/home/skzeng/anaconda3/envs/pp-bd/lib/python3.7/site-packages/paddlespeech/cli/tts/infer.py", line 34, in <module>
    from paddlespeech.t2s.frontend import English
  File "/home/skzeng/anaconda3/envs/pp-bd/lib/python3.7/site-packages/paddlespeech/t2s/__init__.py", line 19, in <module>
    from . import frontend
  File "/home/skzeng/anaconda3/envs/pp-bd/lib/python3.7/site-packages/paddlespeech/t2s/frontend/__init__.py", line 16, in <module>
    from .phonectic import *
  File "/home/skzeng/anaconda3/envs/pp-bd/lib/python3.7/site-packages/paddlespeech/t2s/frontend/phonectic.py", line 20, in <module>
    from g2p_en import G2p
  File "/home/skzeng/anaconda3/envs/pp-bd/lib/python3.7/site-packages/g2p_en/__init__.py", line 1, in <module>
    from .g2p import G2p
  File "/home/skzeng/anaconda3/envs/pp-bd/lib/python3.7/site-packages/g2p_en/g2p.py", line 22, in <module>
    nltk.data.find('taggers/averaged_perceptron_tagger.zip')
  File "/home/skzeng/anaconda3/envs/pp-bd/lib/python3.7/site-packages/nltk/data.py", line 542, in find
    return ZipFilePathPointer(p, zipentry)
  File "/home/skzeng/anaconda3/envs/pp-bd/lib/python3.7/site-packages/nltk/compat.py", line 41, in _decorator
    return init_func(*args, **kwargs)
  File "/home/skzeng/anaconda3/envs/pp-bd/lib/python3.7/site-packages/nltk/data.py", line 394, in __init__
    zipfile = OpenOnDemandZipFile(os.path.abspath(zipfile))
  File "/home/skzeng/anaconda3/envs/pp-bd/lib/python3.7/site-packages/nltk/compat.py", line 41, in _decorator
    return init_func(*args, **kwargs)
  File "/home/skzeng/anaconda3/envs/pp-bd/lib/python3.7/site-packages/nltk/data.py", line 935, in __init__
    zipfile.ZipFile.__init__(self, filename)
  File "/home/skzeng/anaconda3/envs/pp-bd/lib/python3.7/zipfile.py", line 1258, in __init__
    self._RealGetContents()
  File "/home/skzeng/anaconda3/envs/pp-bd/lib/python3.7/zipfile.py", line 1325, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by shnyyds** [comment]
怎么解决的

**Comment by Barsit** [comment]
同问
