### ISSUE TITLE
大神求救，Windows平台报找不到文件的错误呢

### ISSUE THREAD

**Issue by ycy1164656** [JiehangXie/PaddleBoBo#27]
Traceback (most recent call last):
  File "D:\jellyfin\PaddleBoBo\general_demo.py", line 18, in <module>
    video = wav2lip(args.human,wavfile,args.output) #将音频合成到唇形视频
  File "D:\jellyfin\PaddleBoBo\PaddleTools\GAN.py", line 11, in wav2lip
    wav2lip_predictor.run(input_video, input_audio, output)
  File "C:\Users\ycy\AppData\Roaming\Python\Python39\site-packages\ppgan\apps\wav2lip_predictor.py", line 290, in run
    subprocess.call(command, shell=platform.system() != 'Windows')
  File "C:\Program Files\Python39\lib\subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Program Files\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by ycy1164656** [comment]
解决了，ffmpeg要加入环境变量
