### ISSUE TITLE
ValueError: --face argument must be a valid path to video/image file

### ISSUE THREAD

**Issue by yangboz** [JiehangXie/PaddleBoBo#28]
Traceback (most recent call last):
  File "general_demo.py", line 18, in <module>
    video = wav2lip(args.human,wavfile,args.output) #将音频合成到唇形视频
  File "/Users/apple/Downloads/PaddleBoBo-develop/PaddleTools/GAN.py", line 12, in wav2lip
    wav2lip_predictor.run(input_video, input_audio, output)
  File "/Users/apple/miniconda3/envs/py37/lib/python3.7/site-packages/ppgan/apps/wav2lip_predictor.py", line 177, in run
    '--face argument must be a valid path to video/image file')
ValueError: --face argument must be a valid path to video/image file

**Comment by JiehangXie** [comment]
需要先运行前面的表情迁移后才能往下运行。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月9日(星期一) 中午11:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [JiehangXie/PaddleBoBo] ValueError: --face argument must be a valid path to video/image file (Issue #28)





 
Traceback (most recent call last):
 File "general_demo.py", line 18, in 
 video = wav2lip(args.human,wavfile,args.output) #将音频合成到唇形视频
 File "/Users/apple/Downloads/PaddleBoBo-develop/PaddleTools/GAN.py", line 12, in wav2lip
 wav2lip_predictor.run(input_video, input_audio, output)
 File "/Users/apple/miniconda3/envs/py37/lib/python3.7/site-packages/ppgan/apps/wav2lip_predictor.py", line 177, in run
 '--face argument must be a valid path to video/image file')
 ValueError: --face argument must be a valid path to video/image file

**Comment by yangboz** [comment]
thanks.
