### ISSUE TITLE
paddlespeech 报错:  cannot import name 'load' from 'paddleaudio.backends

### ISSUE THREAD

**Issue by xiaoxifei1223** [JiehangXie/PaddleBoBo#45]
我的环境：
paddlepaddle-gpu :2.3.2
ppgan 2.1.0
paddlespeech 1.0.1
paddleaudio 1.0.2

/content/drive/MyDrive/Virtual_broadcast
/usr/local/lib/python3.7/dist-packages/librosa/core/constantq.py:1059: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.complex,
Traceback (most recent call last):
  File "general_demo.py", line 6, in <module>
    from PaddleTools.TTS import TTSExecutor
  File "/content/drive/MyDrive/Virtual_broadcast/PaddleTools/TTS.py", line 10, in <module>
    from paddlespeech.cli.utils import download_and_decompress
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/cli/__init__.py", line 24, in <module>
    from .vector import VectorExecutor
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/cli/vector/__init__.py", line 14, in <module>
    from .infer import VectorExecutor
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/cli/vector/infer.py", line 25, in <module>
    from paddleaudio.backends import load as load_audio
ImportError: cannot import name 'load' from 'paddleaudio.backends' (/usr/local/lib/python3.7/dist-packages/paddleaudio/backends/__init__.py)

**Comment by xiaoxifei1223** [comment]
问题已经解决，主要是paddlespeech 和paddleaudio的版本不一致,按照pypi上两个包的发版时间，挑选一个接近的即可。
the reason is version of paddlespeech is not correct for the paddleaudio

**Comment by xiaoxifei1223** [comment]
问题已经解决，主要是paddlespeech 和paddleaudio的版本不一致,按照pypi上两个包的发版时间，挑选一个接近的即可。
the reason is version of paddlespeech is not correct for the paddleaudio
