### ISSUE TITLE
运行demo报错，提示不能导入某个包

### ISSUE THREAD

**Issue by panghongwei17** [JiehangXie/PaddleBoBo#49]
您好， 执行python general_demo.py
报错。麻烦这个问题如何解决，谢谢 
Traceback (most recent call last):
  File "general_demo.py", line 6, in <module>
    from PaddleTools.TTS import TTSExecutor
  File "/data/hwpang/2020_dev/gan/PaddleBoBo/PaddleTools/TTS.py", line 11, in <module>
    from paddlespeech.cli.utils import MODEL_HOME
ImportError: cannot import name 'MODEL_HOME' from 'paddlespeech.cli.utils' (/root/anaconda3/envs/paddle/lib/python3.8/site-packages/paddlespeech/cli/utils.py)

**Comment by Kedreamix** [comment]
我自己看了看paddlespeech的库，我终于发现了他的改动，在之前的时候，<=1.0的时候，这个都是正确的。但是如果默认下载了1.1或者1.2的版本，在PaddleTools中的TTS.py中，MODEL_HOME就会出现问题，这是因为换位置了，所以我们需要将其换为，ils.env import MODEL_HOME，亲测有效，或者安装paddlespeech为<=1.0的版本也可以，就直接不用改代码了

**Comment by MXF130** [comment]
ImportError: cannot import name 'soft_relu' from 'paddle.fluid.layers.nn' (E:\anaconda\Anaconda\envs\Padd\lib\site-packages\paddle\fluid\layers\nn.py)

又出现了新的错误
