### ISSUE TITLE
您好！新手安装的时候报错了，麻烦帮忙看下 （安装到这一步报错了）

### ISSUE THREAD

**Issue by 15313388469** [JiehangXie/PaddleBoBo#53]
Collecting onnx>=1.6.0
  Using cached onnx-1.12.0.tar.gz (10.1 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      Traceback (most recent call last):
        File "<string>", line 2, in <module>

**Comment by JiehangXie** [comment]
这是自动回复邮件。
 
您好，您的邮件已到达我的邮箱，我将尽快查阅并回复，谢谢。Hello, I have reveived your email. But due to the time differences and my busy work, perhaps I will reply to you in 24 to 48 hours.

**Comment by 15313388469** [comment]
pip install ppgan paddlespeech   在执行这个操作的时候。

**Comment by JiehangXie** [comment]
> pip install ppgan paddlespeech 在执行这个操作的时候。

试下指定版本，pip install paddlespeech==1.0.0

**Comment by 15313388469** [comment]
Collecting matplotlib
  Using cached matplotlib-3.6.3-cp311-cp311-macosx_11_0_arm64.whl (7.2 MB)
Collecting nara-wpe
  Using cached nara_wpe-0.0.9-py3-none-any.whl (33 kB)
ERROR: Could not find a version that satisfies the requirement onnxruntime (from paddlespeech) (from versions: none)
ERROR: No matching distribution found for onnxruntime

指定版本之后开始报这个错了

**Comment by JiehangXie** [comment]
这个应该是onnxruntime的版本问题，我看你的环境下的Mac，这个模型在Mac上是跑不通的，性能不够，建议你用飞桨AIStudio的V100环境运行。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JiehangXie/PaddleBoBo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月1日(星期三) 下午5:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JiehangXie/PaddleBoBo] 您好！新手安装的时候报错了，麻烦帮忙看下 （安装到这一步报错了） (Issue #53)





 
Collecting matplotlib
 Using cached matplotlib-3.6.3-cp311-cp311-macosx_11_0_arm64.whl (7.2 MB)
 Collecting nara-wpe
 Using cached nara_wpe-0.0.9-py3-none-any.whl (33 kB)
 ERROR: Could not find a version that satisfies the requirement onnxruntime (from paddlespeech) (from versions: none)
 ERROR: No matching distribution found for onnxruntime
 
指定版本之后开始报这个错了

**Comment by 15313388469** [comment]
对，我是apple M1 pro  2021 款的。我再试试您说的飞桨AIStudio的V100环境

**Comment by 15313388469** [comment]
> 这个应该是onnxruntime的版本问题，我看你的环境下的Mac，这个模型在Mac上是跑不通的，性能不够，建议你用飞桨AIStudio的V100环境运行。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "JiehangXie/PaddleBoBo" ***@***.***&gt;; 发送时间:&nbsp;2023年2月1日(星期三) 下午5:04 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [JiehangXie/PaddleBoBo] 您好！新手安装的时候报错了，麻烦帮忙看下 （安装到这一步报错了） (Issue #53) Collecting matplotlib Using cached matplotlib-3.6.3-cp311-cp311-macosx_11_0_arm64.whl (7.2 MB) Collecting nara-wpe Using cached nara_wpe-0.0.9-py3-none-any.whl (33 kB) ERROR: Could not find a version that satisfies the requirement onnxruntime (from paddlespeech) (from versions: none) ERROR: No matching distribution found for onnxruntime 指定版本之后开始报这个错了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

你好，我用飞桨平台运行，生成视频没有问题但是没有声音，而且运行让主播说话的那个模块的时候，还是报错了。
from .infer import VectorExecutor
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddlespeech/cli/vector/infer.py", line 25, in <module>
    from paddleaudio.backends import load as load_audio
ImportError: cannot import name 'load' from 'paddleaudio.backends' (/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddleaudio/backends/__init__.py)，
