### ISSUE TITLE
加入声音的时候提示 cannot import name 'soft_relu' from 'paddle.fluid.layers.nn' 求大佬解答

### ISSUE THREAD

**Issue by MXF130** [JiehangXie/PaddleBoBo#66]
E:\PaddleBoBo\PaddleBoBo-0.1>python general_demo.py --human ./file/input/test.mp4 --output ../output.mp4 --text 各位开发者大家好，我是您的专属虚拟主播，很高兴能为您服务。
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\123456.DESKTOP-
[nltk_data]     LB9AMJ9\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger.zip.
E:\anaconda\Anaconda\envs\Padd\lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Traceback (most recent call last):
  File "general_demo.py", line 7, in <module>
    from PaddleTools.GAN import wav2lip
  File "E:\PaddleBoBo\PaddleBoBo-0.1\PaddleTools\GAN.py", line 2, in <module>
    from ppgan.apps.wav2lip_predictor import Wav2LipPredictor
  File "E:\anaconda\Anaconda\envs\Padd\lib\site-packages\ppgan\apps\__init__.py", line 16, in <module>
    from .deepremaster_predictor import DeepRemasterPredictor
  File "E:\anaconda\Anaconda\envs\Padd\lib\site-packages\ppgan\apps\deepremaster_predictor.py", line 24, in <module>
    from ppgan.models.generators.remaster import NetworkR, NetworkC
  File "E:\anaconda\Anaconda\envs\Padd\lib\site-packages\ppgan\models\__init__.py", line 29, in <module>
    from .starganv2_model import StarGANv2Model
  File "E:\anaconda\Anaconda\envs\Padd\lib\site-packages\ppgan\models\starganv2_model.py", line 5, in <module>
    from paddle.fluid.layers.nn import soft_relu
ImportError: cannot import name 'soft_relu' from 'paddle.fluid.layers.nn' (E:\anaconda\Anaconda\envs\Padd\lib\site-packages\paddle\fluid\layers\nn.py)

**Comment by 593527360** [comment]
只能说试试，试一下
pip uninstall paddlepaddle
然后重新安装低版本，我这里装的是2.4.1
pip install paddlepaddle==2.4.1

**Comment by mmhzlrj** [comment]
> 只能说试试，试一下 pip uninstall paddlepaddle 然后重新安装低版本，我这里装的是2.4.1 pip install paddlepaddle==2.4.1

建议删除后用`conda install paddlepaddle==2.4.1 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge`
