### ISSUE TITLE
合成带声音视频发错误

### ISSUE THREAD

**Issue by leecho** [JiehangXie/PaddleBoBo#69]
Traceback (most recent call last):
  File "general_demo.py", line 6, in <module>
    from PaddleTools.TTS import TTSExecutor
  File "/home/aistudio/PaddleBoBo/PaddleTools/TTS.py", line 11, in <module>
    from paddlespeech.cli.utils import MODEL_HOME
ImportError: cannot import name 'MODEL_HOME' from 'paddlespeech.cli.utils' (/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlespeech/cli/utils.py)

<img width="1392" alt="image" src="https://github.com/JiehangXie/PaddleBoBo/assets/5163773/fbccc8af-d8ff-42cb-adc5-de1c684350f3">

**Comment by JiehangXie** [comment]
这是自动回复邮件。
 
您好，您的邮件已到达我的邮箱，我将尽快查阅并回复，谢谢。Hello, I have reveived your email. But due to the time differences and my busy work, perhaps I will reply to you in 24 to 48 hours.

**Comment by ErLongHuDaoGe** [comment]
> Traceback (most recent call last): File "general_demo.py", line 6, in from PaddleTools.TTS import TTSExecutor File "/home/aistudio/PaddleBoBo/PaddleTools/TTS.py", line 11, in from paddlespeech.cli.utils import MODEL_HOME ImportError: cannot import name 'MODEL_HOME' from 'paddlespeech.cli.utils' (/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlespeech/cli/utils.py)
> 
> <img alt="image" width="1392" src="https://user-images.githubusercontent.com/5163773/263963079-fbccc8af-d8ff-42cb-adc5-de1c684350f3.png">

解决了吗，请问，相同的问题

**Comment by JiehangXie** [comment]
这是自动回复邮件。
 
您好，您的邮件已到达我的邮箱，我将尽快查阅并回复，谢谢。Hello, I have reveived your email. But due to the time differences and my busy work, perhaps I will reply to you in 24 to 48 hours.
