### ISSUE TITLE
ImportError: cannot import name 'spectral_norm' from 'paddle.nn.utils' 

### ISSUE THREAD

**Issue by ZeeLyn** [JiehangXie/PaddleBoBo#7]
运行报错，这是什么问题，paddle.nn.utils里确实没有spectral_norm
Traceback (most recent call last):
  File "create_virtual_human.py", line 1, in <module>
    from PaddleTools.GAN import FOM
  File "E:\GitHub\PaddleBoBo\PaddleTools\GAN.py", line 2, in <module>
    from ppgan.apps.wav2lip_predictor import Wav2LipPredictor
  File "C:\Users\ww_19\AppData\Roaming\Python\Python37\site-packages\ppgan\apps\__init__.py", line 16, in <module>
    from .deepremaster_predictor import DeepRemasterPredictor
  File "C:\Users\ww_19\AppData\Roaming\Python\Python37\site-packages\ppgan\apps\deepremaster_predictor.py", line 24, in <module>
    from ppgan.models.generators.remaster import NetworkR, NetworkC
  File "C:\Users\ww_19\AppData\Roaming\Python\Python37\site-packages\ppgan\models\__init__.py", line 15, in <module>
    from .base_model import BaseModel
  File "C:\Users\ww_19\AppData\Roaming\Python\Python37\site-packages\ppgan\models\base_model.py", line 22, in <module>
    from .criterions.builder import build_criterion
  File "C:\Users\ww_19\AppData\Roaming\Python\Python37\site-packages\ppgan\models\criterions\__init__.py", line 3, in <module>
    from .pixel_loss import L1Loss, MSELoss, CharbonnierLoss, \
  File "C:\Users\ww_19\AppData\Roaming\Python\Python37\site-packages\ppgan\models\criterions\pixel_loss.py", line 16, in <module>
    from ..generators.generater_lapstyle import calc_mean_std, mean_variance_norm
  File "C:\Users\ww_19\AppData\Roaming\Python\Python37\site-packages\ppgan\models\generators\__init__.py", line 36, in <module>
    from .gpen import GPEN
  File "C:\Users\ww_19\AppData\Roaming\Python\Python37\site-packages\ppgan\models\generators\gpen.py", line 21, in <module>
    from ppgan.models.discriminators.discriminator_styleganv2 import ConvLayer
  File "C:\Users\ww_19\AppData\Roaming\Python\Python37\site-packages\ppgan\models\discriminators\__init__.py", line 26, in <module>
    from .discriminator_photopen import MultiscaleDiscriminator
  File "C:\Users\ww_19\AppData\Roaming\Python\Python37\site-packages\ppgan\models\discriminators\discriminator_photopen.py", line 22, in <module>
    from paddle.nn.utils import spectral_norm
ImportError: cannot import name 'spectral_norm' from 'paddle.nn.utils' (C:\Users\ww_19\AppData\Roaming\Python\Python37\site-packages\paddle\nn\utils\__init__.py)

**Comment by JiehangXie** [comment]
PaddlePaddle版本太旧了，需要升级到2.2.1，或者建议你直接fork这个项目https://aistudio.baidu.com/aistudio/projectdetail/3280614?contributionType=1&shared=1
