### ISSUE TITLE
本地安装依赖缺少model

### ISSUE THREAD

**Issue by 1320800521** [JiehangXie/PaddleBoBo#72]
我尝试过按照git上的直接pip install ppgan paddlespeech 安装依赖，但是尝试失败，系统为mac os 14.0，本地python版本为3.11.1，
error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/g7/nq59c0f111s54dmslmz013440000gn/T/pip-install-a33kc700/numba_724e042666d244e1a32795c087dac407/setup.py", line 358, in <module>
          metadata['ext_modules'] = get_ext_modules()
                                    ^^^^^^^^^^^^^^^^^
        File "/private/var/folders/g7/nq59c0f111s54dmslmz013440000gn/T/pip-install-a33kc700/numba_724e042666d244e1a32795c087dac407/setup.py", line 98, in get_ext_modules
          import numpy.distutils.misc_util as np_misc
      ModuleNotFoundError: No module named 'numpy'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for numba
  Running setup.py clean for numba
  error: subprocess-exited-with-error

  × python setup.py clean did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/g7/nq59c0f111s54dmslmz013440000gn/T/pip-install-a33kc700/numba_724e042666d244e1a32795c087dac407/setup.py", line 358, in <module>
          metadata['ext_modules'] = get_ext_modules()
                                    ^^^^^^^^^^^^^^^^^
        File "/private/var/folders/g7/nq59c0f111s54dmslmz013440000gn/T/pip-install-a33kc700/numba_724e042666d244e1a32795c087dac407/setup.py", line 98, in get_ext_modules
          import numpy.distutils.misc_util as np_misc
      ModuleNotFoundError: No module named 'numpy'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed cleaning build dir for numba
  Building wheel for llvmlite (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [39 lines of output]
      /opt/homebrew/lib/python3.11/site-packages/setuptools/__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!

              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************

      !!
        dist.fetch_build_eggs(dist.setup_requires)
      running bdist_wheel
      /opt/homebrew/opt/python@3.11/bin/python3.11 /private/var/folders/g7/nq59c0f111s54dmslmz013440000gn/T/pip-install-a33kc700/llvmlite_28f1bdcb17a5456ba7c371618e89f472/ffi/build.py
      LLVM version... Traceback (most recent call last):
        File "/private/var/folders/g7/nq59c0f111s54dmslmz013440000gn/T/pip-install-a33kc700/llvmlite_28f1bdcb17a5456ba7c371618e89f472/ffi/build.py", line 105, in main_posix
          out = subprocess.check_output([llvm_config, '--version'])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 548, in run
          with Popen(*popenargs, **kwargs) as process:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1026, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1950, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/private/var/folders/g7/nq59c0f111s54dmslmz013440000gn/T/pip-install-a33kc700/llvmlite_28f1bdcb17a5456ba7c371618e89f472/ffi/build.py", line 168, in <module>
          main()
        File "/private/var/folders/g7/nq59c0f111s54dmslmz013440000gn/T/pip-install-a33kc700/llvmlite_28f1bdcb17a5456ba7c371618e89f472/ffi/build.py", line 162, in main
          main_posix('osx', '.dylib')
        File "/private/var/folders/g7/nq59c0f111s54dmslmz013440000gn/T/pip-install-a33kc700/llvmlite_28f1bdcb17a5456ba7c371618e89f472/ffi/build.py", line 107, in main_posix
          raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
      RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
      error: command '/opt/homebrew/opt/python@3.11/bin/python3.11' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build numba llvmlite
ERROR: Could not build wheels for numba, llvmlite, which is required to install pyproject.toml-based projects

当我尝试按照 https://aistudio.baidu.com/projectdetail/5198874?channelType=0&channel=0 上步骤执行时，出现类似问题，当我在Pycharm中运行时，也出现一下问题
 itsdangerous, fsspec, filelock, dill, click, blinker, annotated-types, aiohttp, xxhash, scikit-learn, regex, pyparsing, pydantic, pycryptodome, pyarrow-hotfix, pyarrow, ppft, pox, pillow, pandas, numba, multiprocess, kiwisolver, huggingface-hub, future, fonttools, flask, cycler, contourpy, cffi, Babel, tifffile, tabulate, soundfile, seqeval, sentencepiece, resampy, rarfile, psutil, protobuf, portalocker, pathos, paddlefsl, paddle2onnx, nltk, networkx, mock, matplotlib, lxml, lazy-loader, jieba, inflect, imageio, Flask-Babel, distance, decorator, datasets, cython, colorlog, colorama, bottleneck, bce-python-sdk, audioread, yacs, webrtcvad, visualdl, typeguard, timer, textgrid, scikit-image, sacrebleu, pyworld, pypinyin, praatio, paddlespeech-feat, paddlenlp, paddleaudio, opencv-python, nara-wpe, munch, loguru, librosa, kaldiio, jsonlines, imageio-ffmpeg, h5py, g2pM, g2p-en, editdistance, easydict, ppgan, paddlespeech
    Running setup.py install for llvmlite ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/beijingchaoyang/PaddleBoBo/venv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/g7/nq59c0f111s54dmslmz013440000gn/T/pip-install-du6ejrpv/llvmlite_ca62a8d4e141437d834a6b4aa17925c4/setup.py'"'"'; __file__='"'"'/private/var/folders/g7/nq59c0f111s54dmslmz013440000gn/T/pip-install-du6ejrpv/llvmlite_ca62a8d4e141437d834a6b4aa17925c4/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/g7/nq59c0f111s54dmslmz013440000gn/T/pip-record-_tt9cf5e/install-record.txt --single-version-externally-managed --compile --install-headers /Users/beijingchaoyang/PaddleBoBo/venv/include/site/python3.10/llvmlite
         cwd: /private/var/folders/g7/nq59c0f111s54dmslmz013440000gn/T/pip-install-du6ejrpv/llvmlite_ca62a8d4e141437d834a6b4aa17925c4/
    Complete output (29 lines):
    running install
    running build
    got version from file /private/var/folders/g7/nq59c0f111s54dmslmz013440000gn/T/pip-install-du6ejrpv/llvmlite_ca62a8d4e141437d834a6b4aa17925c4/llvmlite/_version.py {'version': '0.31.0', 'full': 'fe7d985f6421d87f613bd414479d29d912771562'}
    running build_ext
    /Users/beijingchaoyang/PaddleBoBo/venv/bin/python /private/var/folders/g7/nq59c0f111s54dmslmz013440000gn/T/pip-install-du6ejrpv/llvmlite_ca62a8d4e141437d834a6b4aa17925c4/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/private/var/folders/g7/nq59c0f111s54dmslmz013440000gn/T/pip-install-du6ejrpv/llvmlite_ca62a8d4e141437d834a6b4aa17925c4/ffi/build.py", line 105, in main_posix
        out = subprocess.check_output([llvm_config, '--version'])
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 420, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 501, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 966, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1842, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/private/var/folders/g7/nq59c0f111s54dmslmz013440000gn/T/pip-install-du6ejrpv/llvmlite_ca62a8d4e141437d834a6b4aa17925c4/ffi/build.py", line 168, in <module>
        main()
      File "/private/var/folders/g7/nq59c0f111s54dmslmz013440000gn/T/pip-install-du6ejrpv/llvmlite_ca62a8d4e141437d834a6b4aa17925c4/ffi/build.py", line 162, in main
        main_posix('osx', '.dylib')
      File "/private/var/folders/g7/nq59c0f111s54dmslmz013440000gn/T/pip-install-du6ejrpv/llvmlite_ca62a8d4e141437d834a6b4aa17925c4/ffi/build.py", line 107, in main_posix
        raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
    error: command '/Users/beijingchaoyang/PaddleBoBo/venv/bin/python' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/beijingchaoyang/PaddleBoBo/venv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/g7/nq59c0f111s54dmslmz013440000gn/T/pip-install-du6ejrpv/llvmlite_ca62a8d4e141437d834a6b4aa17925c4/setup.py'"'"'; __file__='"'"'/private/var/folders/g7/nq59c0f111s54dmslmz013440000gn/T/pip-install-du6ejrpv/llvmlite_ca62a8d4e141437d834a6b4aa17925c4/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/g7/nq59c0f111s54dmslmz013440000gn/T/pip-record-_tt9cf5e/install-record.txt --single-version-externally-managed --compile --install-headers /Users/beijingchaoyang/PaddleBoBo/venv/include/site/python3.10/llvmlite Check the logs for full command output.

请问，对环境、cpu、内存、python版本等有什么要求吗？没看到在哪里写

**Comment by 1320800521** [comment]
这个问题是 2023 年的本地依赖安装环境问题，我现在已经不再使用当时那套环境和版本，问题也不再具有当前复现条件。为避免留下过期 issue，先关闭。感谢。
