### ISSUE TITLE
运行 python create_virtual_human.py --config default.yaml 报错

### ISSUE THREAD

**Issue by Chenkeyi43** [JiehangXie/PaddleBoBo#76]
λ 9b9b5ebf930e /PaddleBoBo python create_virtual_human.py --config default.yaml --use_cpu=True
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
[03/01 07:44:38] ppgan INFO: Found /root/.cache/ppgan/GPEN-512.pdparams
W0301 07:44:38.826195   212 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 8.9, Driver API Version: 12.3, Runtime API Version: 11.2
W0301 07:44:38.827821   212 device_context.cc:465] device: 0, cuDNN Version: 8.1.
Traceback (most recent call last):
  File "create_virtual_human.py", line 1, in <module>
    from PaddleTools.GAN import FOM
  File "/PaddleBoBo/PaddleTools/GAN.py", line 8, in <module>
    face_enhancement = True)
  File "/usr/local/lib/python3.7/dist-packages/ppgan/apps/wav2lip_predictor.py", line 49, in __init__
    self.faceenhancer = FaceEnhancement()
  File "/usr/local/lib/python3.7/dist-packages/ppgan/faceutils/face_enhancement/face_enhance.py", line 42, in __init__
    self.face_enhance = GPEN(size=512, style_dim=512, n_mlp=8)
  File "/usr/local/lib/python3.7/dist-packages/ppgan/models/generators/gpen.py", line 54, in __init__
    is_concat=True)
  File "/usr/local/lib/python3.7/dist-packages/ppgan/models/generators/generator_styleganv2.py", line 263, in __init__
    activation="fused_lrelu"))
  File "/usr/local/lib/python3.7/dist-packages/ppgan/modules/equalized.py", line 87, in __init__
    (in_dim, out_dim), default_initializer=nn.initializer.Normal())
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 422, in create_parameter
    default_initializer)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layer_helper_base.py", line 378, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 3137, in create_parameter
    initializer(param, self)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/initializer.py", line 362, in __call__
    stop_gradient=True)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 3167, in append_op
    kwargs.get("stop_gradient", False))
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/tracer.py", line 45, in trace_op
    not stop_gradient)
OSError: (External) CUSOLVER error(7). 
  [Hint: 'CUSOLVER_STATUS_INTERNAL_ERROR'. An internal cuSolver operation failed. This error is usually caused by a cudaMemcpyAsync() failure.To correct: check that the hardware, an appropriate version of the driver, and the cuSolver library are correctly installed. Also, check that the memory passed as a parameter to the routine is not being deallocated prior to the routine’s completion.] (at /paddle/paddle/fluid/platform/device_context.h:418)
  [operator < gaussian_random > error]

λ 9b9b5ebf930e /PaddleBoBo nvidia-smi 
Fri Mar  1 07:46:41 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.23.08              Driver Version: 545.23.08    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090        On  | 00000000:01:00.0 Off |                  Off |
| 31%   26C    P8               7W / 450W |  12438MiB / 24564MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
+---------------------------------------------------------------------------------------+

想知道是显存不够吗，在AISTDIO 中就能执行

**Comment by JeromeD3** [comment]
这项目不维护了吗
